Stopping Execution.... Check traceback below
Traceback (most recent call last):
  File "run_PIZSA.py", line 42, in <module>
    scripts.src_main.main.main()
  File "/home/yavuz/yavuz_proje/protac/deneme/PIZSA/scripts/src_main/main.py", line 103, in main
    predict_binding_all(parent_dir, input_file, pot_dict, z_threshold, output_file, options)
  File "/home/yavuz/yavuz_proje/protac/deneme/PIZSA/scripts/src_main/predict_binding.py", line 196, in predict_binding_all
    mod_output = write_out(output_file, mod_out_val, options, mod_num_interactors, mod_native_score, z_threshold, mod_1, mod_respair_scores, warnings, opt_alpha_fraction)
  File "/home/yavuz/yavuz_proje/protac/deneme/PIZSA/scripts/src_main/write_out.py", line 33, in write_out
    sys.stdout = open(out_score_file, 'w')
IOError: [Errno 2] No such file or directory: '/home/yavuz/yavuz_proje/protac/outputs/Megadock_OUT/pizsa/5t35-DA_target_input_710_complex._scores.txt5t35-DA_target_input_710_complex._scores.txt'
